SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  GC_SuppressionSystem "{684E2A62F38CECCD}" {
   m_fRecoveryDelay 0.5
   m_fRecoveryRate 0.18
   m_fMaxRange 15
   m_fFlinchRange 5
   m_fFlinchShakeMultiplier 0.5
   m_fFlinchShakeSuppressedMultiplier 1
   m_fFlinchShakeADSMultiplier 0.2
   m_fMassMultiplier 10
   m_fBaseSuppressionMultiplier 0.2
   m_fExplosionScreenShakeMultiplier 2.5
   m_fExplosionScreenShakeMaxAmount 15
  }
  SR_StanceTimeout "{6968965256DD079E}" {
   SystemLocation Client
   WEIGHT_COEFFICIENT 50
  }
 }
}