MenuManager {
 MenuPresets {
  MenuPreset SRGP_WeaponDisplacementSettings {
   Layout "{ED33315E6A6F2F26}UI/layouts/Menus/SettingsMenu/SRGP_GameplaySettings.layout"
   Class "SRGP_WeaponDisplacementSettings"
  }
 }
}