SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{6A1B35A931402917}" {
   m_sName "EH_Gunplay"
   m_sDisplayName "EH_Gunplay"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{6A1B35A93FF3FD2D}" {
    }
   }
  }
 }
}